version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: ${DATABASE_NAME}
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3

  infrastructure:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVICE_PORT}:${RUN_SERVER_PORT}"
    volumes:
      - .:/app
    env_file:
      - path: .env
        required: true
    depends_on:
      db:
        condition: service_healthy
